cc_test(
    name = 'test_sort',
    srcs = [
        "test_sort.c",
    ],
    deps = [
        "//base:base"
    ]
)
cc_test(
    name = 'test_toys_list',
    srcs = [
        "test_toys_list.c",
    ],
    deps = [
        "//base:base"
    ]
)

cc_test(
    name = 'test_toys_sds',
    srcs = [
        "test_toys_sds.c",
    ],
    deps = [
        "//base:base"
    ]
)
