cc_test(
    name = 'test_echo_client',
    srcs = [
        "test_echo_client.c",
    ],
    deps = [
        "//echo_server:echo_server_library"
    ]
)
cc_test(
    name = 'test_echo_server',
    srcs = [
        "test_echo_server.c",
    ],
    deps = [
        "//echo_server:echo_server_library"
    ]
)

